import { Link } from 'react-router-dom'
import { useEffect } from 'react'
import './DictionaryEntry.css'

const FAQ_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What does an asymmetrical expression mean?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'An asymmetrical expression is when one side of the face shows more movement or intensity than the other during an emotional reaction, often suggesting the expression is partly performed rather than fully spontaneous.',
      },
    },
    {
      '@type': 'Question',
      name: 'Is facial asymmetry always a sign of dishonesty?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'No. Many people have naturally asymmetrical faces at rest. The signal becomes meaningful only when the asymmetry appears specifically during an active emotional expression rather than as a permanent facial feature.',
      },
    },
  ],
}

export default function DictAsymmetricalExpression() {
  useEffect(() => {
    const script = document.createElement('script')
    script.type = 'application/ld+json'
    script.text = JSON.stringify(FAQ_SCHEMA)
    document.head.appendChild(script)
    return () => {
      document.head.removeChild(script)
    }
  }, [])

  return (
    <main className="de-page">
      <Link to="/dictionary" className="de-back-link">← Back to Dictionary</Link>

      <header className="de-header">
        <span className="de-category">Deception Signals</span>
        <h1 className="de-title">Asymmetrical Expression</h1>
        <p className="de-lead">
          An asymmetrical expression occurs when one side of the face displays noticeably more
          movement or intensity than the other during an emotional reaction. Genuine, spontaneous
          emotional expressions are produced by the subcortical regions of the brain and tend to
          activate both sides of the face symmetrically and simultaneously. Expressions that are
          consciously produced or partially performed are generated by different neural pathways and
          often fail to achieve this same symmetry, resulting in a lopsided quality that can be
          subtle but is detectable with attention. A one sided smile, an eyebrow that rises higher on
          one side than the other, or a mouth that pulls more strongly to one side during a reaction
          are all examples of this asymmetry. It does not automatically prove deception on its own,
          but it is one of several signals that trained observers use to judge whether an emotional
          display is fully genuine or has been consciously shaped for the benefit of an audience.
        </p>
      </header>

      <section className="de-section">
        <h2 className="de-h2">What To Look For</h2>
        <ul className="de-list">
          <li>A smile, frown or other expression that appears stronger or more pronounced on one side of the face</li>
          <li>Eyebrows that raise or lower unevenly rather than moving together</li>
          <li>An expression that looks slightly lopsided rather than fully symmetrical at its peak</li>
          <li>A mismatch between the emotion being described in words and the asymmetry visible on the face</li>
        </ul>
      </section>

      <section className="de-section">
        <h2 className="de-h2">What It Means In Context</h2>
        <p className="de-text">
          Asymmetry becomes more significant when it appears at a moment where a fully genuine
          reaction would be expected, such as reacting to unexpected news or being asked a direct
          question about something personal. A slightly asymmetrical resting face is simply normal
          human anatomy for many people, since almost no face is perfectly symmetrical at rest. The
          signal is far more meaningful when it appears specifically during an active emotional
          expression rather than as a permanent facial feature, and even more meaningful when it
          appears alongside other signals such as a delayed or held expression that does not fade
          naturally.
        </p>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Related Signals</h2>
        <div className="de-related-grid">
          <Link to="/dictionary/blank-stare" className="de-related-chip">Blank Stare</Link>
          <Link to="/dictionary/blinking-rate-increase" className="de-related-chip">Blinking Rate Increase</Link>
          <Link to="/dictionary/body-orientation" className="de-related-chip">Body Orientation</Link>
        </div>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Learn More</h2>
        <div className="de-cta">
          <p className="de-cta-text">
            Facial asymmetry is one of the deception signals covered in depth in our guide to
            spotting a liar, alongside clusters, timing and contradiction cues.
          </p>
          <Link to="/guides/spot-a-liar" className="de-cta-btn">
            Read the How to Spot a Liar Guide
          </Link>
        </div>
      </section>
    </main>
  )
}
