import { Link } from 'react-router-dom'
import { useEffect } from 'react'
import './DictionaryEntry.css'

const FAQ_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is a contempt micro expression?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A contempt micro expression is a brief, involuntary facial movement in which one corner of the mouth rises higher than the other, signalling genuine underlying contempt or a feeling of superiority.',
      },
    },
    {
      '@type': 'Question',
      name: 'Why is a contempt micro expression considered reliable?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Because it is produced involuntarily by the same system responsible for other spontaneous facial expressions, it is extremely difficult to consciously fake or suppress, unlike a deliberate smirk.',
      },
    },
  ],
}

export default function DictContemptMicroExpression() {
  useEffect(() => {
    const script = document.createElement('script')
    script.type = 'application/ld+json'
    script.text = JSON.stringify(FAQ_SCHEMA)
    document.head.appendChild(script)
    return () => {
      document.head.removeChild(script)
    }
  }, [])

  return (
    <main className="de-page">
      <Link to="/dictionary" className="de-back-link">← Back to Dictionary</Link>

      <header className="de-header">
        <span className="de-category">Deception Signals</span>
        <h1 className="de-title">Contempt Micro Expression</h1>
        <p className="de-lead">
          A contempt micro expression is an extremely brief, involuntary facial movement in which
          one corner of the mouth tightens and rises slightly higher than the other, producing an
          asymmetrical, almost sneering quality that lasts only a fraction of a second. Unlike posed
          expressions of contempt, which tend to be held and symmetrical, the genuine micro
          expression appears and disappears so quickly that it is easily missed without deliberate
          attention or training. Because it is generated by the same involuntary emotional system
          responsible for other spontaneous facial expressions, it is extremely difficult to
          consciously produce or suppress, which makes it one of the more scientifically validated
          indicators of genuine underlying contempt or a feeling of superiority toward another person
          or their statement. This micro expression frequently appears at precise moments, such as
          immediately after hearing a statement the person privately disagrees with or considers
          beneath serious consideration, before a managed neutral expression quickly reasserts
          itself. Its brevity and asymmetry are what distinguish it from a fully posed, deliberate
          smirk.
        </p>
      </header>

      <section className="de-section">
        <h2 className="de-h2">What To Look For</h2>
        <ul className="de-list">
          <li>A brief, one sided raise at the corner of the mouth lasting a fraction of a second</li>
          <li>The expression appearing immediately after a specific statement or question</li>
          <li>A quick return to a neutral or composed expression once the flash has passed</li>
          <li>The asymmetry of the mouth distinguishing it from a fully posed, deliberate smirk</li>
        </ul>
      </section>

      <section className="de-section">
        <h2 className="de-h2">What It Means In Context</h2>
        <p className="de-text">
          A contempt micro expression appearing at the exact moment a particular claim or statement
          is made is a strong indicator that the underlying feeling is directed at that specific
          content rather than being incidental. The same asymmetrical mouth movement held for a
          longer, deliberate duration is more likely to be a conscious smirk rather than a genuine
          involuntary reaction. In negotiation, relationship and workplace settings, catching this
          fleeting expression at the precise moment it occurs often reveals a private reaction that a
          person has no intention of expressing openly.
        </p>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Related Signals</h2>
        <div className="de-related-grid">
          <Link to="/dictionary/asymmetrical-expression" className="de-related-chip">Asymmetrical Expression</Link>
          <Link to="/dictionary/brow-raise" className="de-related-chip">Brow Raise</Link>
          <Link to="/dictionary/chin-stroking" className="de-related-chip">Chin Stroking</Link>
        </div>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Learn More</h2>
        <div className="de-cta">
          <p className="de-cta-text">
            Contempt is one of the most damaging signals in any disagreement. Our guide covers this
            in depth alongside escalation, withdrawal and resolution signals.
          </p>
          <Link to="/guides/arguments" className="de-cta-btn">
            Read the Reading Body Language in Arguments Guide
          </Link>
        </div>
      </section>
    </main>
  )
}
