import { Link } from 'react-router-dom'
import { useEffect } from 'react'
import './DictionaryEntry.css'

const FAQ_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is a facial symmetry check in body language?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A facial symmetry check is a technique that compares both sides of the face during an emotional expression to assess whether the display is genuine or partly performed.',
      },
    },
    {
      '@type': 'Question',
      name: 'Why does facial asymmetry suggest an expression might not be genuine?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Genuine expressions are produced by brain regions that activate both sides of the face symmetrically, while performed expressions are generated differently and often struggle to achieve the same symmetry.',
      },
    },
  ],
}

export default function DictFacialSymmetryCheck() {
  useEffect(() => {
    const script = document.createElement('script')
    script.type = 'application/ld+json'
    script.text = JSON.stringify(FAQ_SCHEMA)
    document.head.appendChild(script)
    return () => {
      document.head.removeChild(script)
    }
  }, [])

  return (
    <main className="de-page">
      <Link to="/dictionary" className="de-back-link">← Back to Dictionary</Link>

      <header className="de-header">
        <span className="de-category">Deception Signals</span>
        <h1 className="de-title">Facial Symmetry Check</h1>
        <p className="de-lead">
          A facial symmetry check is a deliberate technique used in deception detection that
          involves comparing both sides of a person's face during an emotional expression to assess
          whether the display appears genuine or consciously constructed. Genuine, spontaneous
          emotional expressions are generated by subcortical brain regions and tend to produce close
          to symmetrical movement across both sides of the face simultaneously, while expressions
          that are partially or fully performed are often generated through different neural pathways
          that struggle to achieve the same precise symmetry. Trained observers performing a facial
          symmetry check will look specifically at features such as the corners of the mouth, the
          raising of the eyebrows and the crinkling around the eyes, comparing the left and right
          sides for subtle differences in timing, intensity or duration. While mild natural asymmetry
          exists in almost every face at rest and does not itself indicate anything, a pronounced or
          unusual asymmetry appearing specifically during an active emotional display, particularly
          one that would normally be expected to look genuine, is a meaningful signal worth further
          attention rather than a definitive proof of deception on its own.
        </p>
      </header>

      <section className="de-section">
        <h2 className="de-h2">What To Look For</h2>
        <ul className="de-list">
          <li>Comparing the left and right sides of the face during an active emotional expression</li>
          <li>Looking specifically at the mouth corners, eyebrows and the area around the eyes</li>
          <li>Noting differences in timing, intensity or duration between the two sides of the face</li>
          <li>Distinguishing this from ordinary resting asymmetry that most faces display naturally</li>
        </ul>
      </section>

      <section className="de-section">
        <h2 className="de-h2">What It Means In Context</h2>
        <p className="de-text">
          A facial symmetry check performed on a person's resting expression is not particularly
          useful, since almost every face shows some natural asymmetry even with no emotion being
          expressed at all. The technique becomes genuinely informative when applied specifically to
          an active emotional display, comparing how symmetrically and simultaneously both sides of
          the face move during that specific expression, since a pronounced asymmetry appearing only
          during the emotional display itself is what suggests the expression may be at least partly
          performed rather than fully spontaneous.
        </p>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Related Signals</h2>
        <div className="de-related-grid">
          <Link to="/dictionary/asymmetrical-expression" className="de-related-chip">Asymmetrical Expression</Link>
          <Link to="/dictionary/contempt-micro-expression" className="de-related-chip">Contempt Micro Expression</Link>
          <Link to="/dictionary/eye-contact-avoidance" className="de-related-chip">Eye Contact Avoidance</Link>
        </div>
      </section>

      <section className="de-section">
        <h2 className="de-h2">Learn More</h2>
        <div className="de-cta">
          <p className="de-cta-text">
            Reliable deception detection means fact checking against science, not popular myths. Our
            guide covers what actually holds up under research.
          </p>
          <Link to="/guides/myths" className="de-cta-btn">
            Read the Body Language Myths Debunked Guide
          </Link>
        </div>
      </section>
    </main>
  )
}
